### ISSUE TITLE
Delegation was not found

### ISSUE THREAD

**Issue by jsczczc** [PublicFreeSuffix/PublicFreeSuffix#310]
I want to host my domain on [he.net](https://he.net/), but it keeps showing the error "Delegation was not found" as shown in the picture. Does it need some time to take effect? Approximately how long will it take? Please help solve this problem.

<img width="846" height="507" alt="Image" src="https://github.com/user-attachments/assets/a07c8aa2-267f-4789-b9ba-a148183946b2" />

**Comment by PublicFreeSuffix** [comment]
@jsczczc  This issue has been resolved (due to a network error, your previous pull request failed to sync to your PDA. This has now been restored). Your current NS records are: "ns1.desec.io" and "ns2.desec.org."
If you still need to use he.net, you can resubmit your pull request now, confirm the update, and then go to he.net to add the domain.

**Comment by jsczczc** [comment]
Thank you for your reply. I have just resubmitted the pull request and confirmed the update to he.net. The system showed:

DNS Sync Successful
Operation Type: update
Domain: haczc.6ti.net
Nameservers: ns1.he.net, ns2.he.net, ns3.he.net, ns4.he.net, ns5.he.net
Message: Successfully updated NS records for haczc.6ti.net
Time: 8/4/2025, 2:33:58 AM

However, I still cannot add the domain haczc.6ti.net on he.net. Do I need to wait a bit longer, or is there still another issue that needs to be resolved?

**Comment by jsczczc** [comment]
It’s all resolved now. Thanks!
